name = "azure"
description = "Commands for deploying Spin applications to Azure Kubernetes Service (AKS) with workload identity."
version = "0.1.0"
spin_compatibility = ">=2.3.1"
license = "Apache-2.0"
homepage = "https://github.com/mossaka/spin-plugin-azure"
package = "./bin/spin-azure" 